---
- name: Ensure the apt cache is up to date
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: provisioning probes
  hosts: all
  roles:
    - ansible-role-pssid-VT-tools
    - ansible-role-pssid-daemon

