- src: https://github.com/UMNET-perfSONAR/ansible-role-pscheduler-5-ubuntu
- src: https://github.com/UMNET-perfSONAR/ansible-role-pscheduler-tool-umichwpa-secrets
- src: https://github.com/UMNET-perfSONAR/ansible-role-pssid
